{% set name = "manhole" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/manhole-{{ version }}.tar.gz
  sha256: bada20a25b547b395d472e2e08928f0437df26bbdbda4797c55863198e29a21f

build:
  entry_points:
    - manhole-cli = manhole.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 4

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - __unix

test:
  imports:
    - manhole
  commands:
    - pip check
    - manhole-cli --help
  requires:
    - pip

about:
  home: https://github.com/ionelmc/python-manhole
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Debugging manhole for python applications

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
